In [2]:
import pandas as pd
import geopandas as gpd
pd.set_option('display.max_columns', None)

In [3]:
denue = gpd.read_file('../docs/datos/unidades_economicas_cdit_2025.geojson')
denue.head(1)

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,nom_v_e_1,tipo_v_e_2,nom_v_e_2,tipo_v_e_3,nom_v_e_3,numero_ext,letra_ext,edificio,edificio_e,numero_int,letra_int,tipo_asent,nomb_asent,tipoCenCom,nom_CenCom,num_local,cod_postal,cve_ent,entidad,cve_mun,municipio,cve_loc,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta,layer,path,cod_sector,sector,cod_subsector,subsector,cod_rama,rama,cod_subrama,subrama,clase,categoria_cdit,geometry
0,652551,09005811219000291000000000U0,ESPI,None,466211,"Comercio al por menor de mobiliario, equipo y ...",0 a 5 personas,CALLE,21,CALLE,PERLILLAR,EJE VIAL,CENTRAL (LAZARO CARDENAS),CALLE,20,2,None,None,None,0,None,COLONIA,PRO NACIONAL,None,None,None,07600,09,Ciudad de M�xico,005,Gustavo A. Madero,0001,Gustavo A. Madero,0440,024,None,None,None,Fijo,19.517233,-99.155983,2010-07,denue_09_shp — conjunto_de_datos/denue_inegi_0...,/vsizip/C:\Users\COMIMSA\Downloads\denue_09_sh...,46,Comercio al por menor,466,"Comercio al por menor de enseres domésticos, c...",4662,"Comercio al por menor de mobiliario, equipo y ...",46621,"Comercio al por menor de mobiliario, equipo y ...","Comercio al por menor de mobiliario, equipo y ...","Tecnología, informática y telecomunicaciones",POINT (-99.15598 19.51723)

In [4]:
denue['categoria_cdit'].value_counts()

categoria_cdit
Educación y capacitación                           1023
Servicios profesionales, científicos y técnicos     569
Tecnología, informática y telecomunicaciones        481
Apoyo a negocios y emprendimiento                   362
Manufactura tecnológica e industria avanzada        262
Diseño y economía creativa                          220
Name: count, dtype: int64

In [ ]:
# edu = denue[denue['categoria_cdit'].str.contains('edu', case=False, na=False)]
edu = denue[denue['categoria_cdit'] == 'Educación y capacitación']

print(edu.shape)
edu.head(1)

(1023, 55)

,id,clee,nom_estab,raz_social,codigo_act,nombre_act,per_ocu,tipo_vial,nom_vial,tipo_v_e_1,nom_v_e_1,tipo_v_e_2,nom_v_e_2,tipo_v_e_3,nom_v_e_3,numero_ext,letra_ext,edificio,edificio_e,numero_int,letra_int,tipo_asent,nomb_asent,tipoCenCom,nom_CenCom,num_local,cod_postal,cve_ent,entidad,cve_mun,municipio,cve_loc,localidad,ageb,manzana,telefono,correoelec,www,tipoUniEco,latitud,longitud,fecha_alta,layer,path,cod_sector,sector,cod_subsector,subsector,cod_rama,rama,cod_subrama,subrama,clase,categoria_cdit,geometry
1,9704974,15104611611000771000000000U4,CLASES DE MUSICA,None,611611,Escuelas de arte del sector privado,0 a 5 personas,CALLE,CALLE DEL CRISTO,AVENIDA,SANTA MONICA,CALLE,DIEZ DE MAYO,CALLE,VIA GUSTAVO BAZ,10,None,None,None,None,None,COLONIA,EL MIRADOR,None,None,None,54080,15,M�xico,104,Tlalnepantla de Baz,0001,Tlalnepantla,0961,006,5537643645,LAAXX@GMAIL.COM,None,Fijo,19.512164,-99.219365,2024-11,denue_15_2_shp — conjunto_de_datos/denue_inegi...,/vsizip/C:\Users\COMIMSA\Downloads\denue_15_2_...,61,Servicios educativos,611,Servicios educativos,6116,Otros servicios educativos,61161,Escuelas de arte,Escuelas de arte del sector privado,Educación y capacitación,POINT (-99.21936 19.51216)

In [12]:
edu['subrama'].value_counts()

subrama
Escuelas de educación primaria                                                                           254
Escuelas de educación preescolar y centros de estimulación temprana                                      231
Escuelas de educación superior                                                                            92
Escuelas de educación secundaria general                                                                  76
Otros servicios educativos                                                                                63
Escuelas que combinan diversos niveles de educación                                                       61
Escuelas de arte                                                                                          55
Escuelas de deporte                                                                                       43
Escuelas de educación media superior                                                                      41
Escuelas de educación para necesidades especiales                                                         33
Escuelas de oficios                                                                                       24
Escuelas de educación secundaria técnica                                                                  18
Escuelas de idiomas                                                                                       15
Escuelas de educación técnica superior                                                                     5
Escuelas para la capacitación de ejecutivos                                                                5
Escuelas de educación media técnica terminal                                                               3
Servicios de capacitación para el trabajo para personas desempleadas, subempleadas o con discapacidad      2
Escuelas de computación                                                                                    2
Name: count, dtype: int64

In [15]:
categorias = ['Escuelas de educación primaria', 
              'Escuelas de educación secundaria general',
              'Escuelas de educación secundaria técnica',
              'Escuelas de educación media técnica terminal',
              'Escuelas de educación media superior', 
              'Escuelas de educación superior',
              'Escuelas de educación técnica superior', 
              'Escuelas que combinan diversos niveles de educación']

edu_1 = edu[edu['subrama'].isin(categorias)].copy()

nivel_map = {
    'Escuelas de educación primaria':                        'Educación básica',
    'Escuelas de educación secundaria general':              'Educación básica',
    'Escuelas de educación secundaria técnica':              'Educación básica',
    'Escuelas de educación media superior':                  'Educación media',
    'Escuelas de educación media técnica terminal':          'Educación media',
    'Escuelas de educación superior':                        'Educación superior',
    'Escuelas de educación técnica superior':                'Educación superior',
    'Escuelas que combinan diversos niveles de educación':   'Multinivel',
}

edu_1['nivel_educativo'] = edu_1['subrama'].map(nivel_map)

edu_1['nivel_educativo'].value_counts()

nivel_educativo
Educación básica      348
Educación superior     97
Multinivel             61
Educación media        44
Name: count, dtype: int64

In [16]:
edu.to_crs(epsg=4326).to_file('../docs/datos/ue_educativas_cdit_2025.geojson')